version: "3"
services:

        jenkins:
            image: jenkinsci/jenkins
            ports:
              - "8080:8080"
            container_name : jenkins
            volumes:
              - ./jenkins:/var/jenkins_home:rw
        
        artifactory:
           image: mattgruter/artifactory
           ports:
             - 8081:8080
           container_name: artifactory
           depends_on:
             - jenkins
           volumes:
                   - ./artifactory/:/artifactory:rw
